private_bookshelf/bookshelf/urls.py
from django.urls import path
from . import views

app_name = 'bookshelf'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('book-list/', views.BookshelfListView.as_view(), name="book_list"),
    path('book-detail/<int:pk>/', views.BookshelfDetailView.as_view(), name="book_detail"),
    path('book-create/', views.BookshelfCreateView.as_view(), name="book_create"),
    path('book-update/<int:pk>/', views.BookshelfUpdateView.as_view(), name="book_update"),
    path('book-delete/<int:pk>/', views.BookshelfDeleteView.as_view(), name="book_delete"),
]

private_bookshelf/private_bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookshelf.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

# # DEBUG TOOL BAR の設定
# if settings_dev.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

private_bookshelf/accounts/models.py
from django.db import models

# Create your models here.

private_bookshelf/bookshelf/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Bookshelf(models.Model):
    """日記モデル"""

    user = models.ForeignKey(User, verbose_name="ユーザー", on_delete= models.PROTECT)
    title = models.CharField(verbose_name="タイトル", max_length= 100)
    auther = models.CharField(verbose_name="著作者", max_length= 100)
    publisher = models.CharField(verbose_name="出版社", blank=True, null= True, max_length= 100)
    isbnum = models.CharField(verbose_name="ISBN", blank=True, null= True, max_length= 100)
    comment = models.TextField(verbose_name="コメント", blank=True, null= True)
    group = models.CharField(verbose_name="グループ", max_length= 100, default="None")
    readpage = models.CharField(verbose_name="しおり", default= "0ページ", max_length= 100)
    evaluation = models.IntegerField(verbose_name="評価", blank=True, null= True, validators=[MinValueValidator(1), MaxValueValidator(5)])
    photo = models.ImageField(verbose_name="写真", blank=True, null= True)
    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add= True)
    updated_at = models.DateTimeField(verbose_name="更新日時", auto_now= True)

    class Meta:
        verbose_name_plural = "Bookshelf"

    def __str__(self):
        return self.title

private_bookshelf/bookshelf/forms.py
from bookshelf.models import Bookshelf
from django import forms
from django.core.mail import EmailMessage

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'
        
    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'info.mbshelf@gmail.com'
        to_list = [
            
        ]
        cc_list = [
            
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class BookshelfCreateForm(forms.ModelForm):
    class Meta:
        model = Bookshelf
        fields = ('title', 'auther', 'publisher', 'isbnum', 'comment', 'readpage', 'group', 'evaluation', 'photo', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        
        self.fields['title'].widget.attrs['placeholder'] = '入力は必須です。'
        self.fields['auther'].widget.attrs['placeholder'] = '入力は必須です。'
        self.fields['evaluation'].widget.attrs['placeholder'] = '1から５の間で評価を入力してください。'

private_bookshelf/accounts/views.py
from django.shortcuts import render

# Create your views here.

private_bookshelf/bookshelf/views.py
import logging
logger = logging.getLogger(__name__)

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .forms import InquiryForm, BookshelfCreateForm
from .models import Bookshelf
from django.db.models import Q

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy("bookshelf:inquiry")

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

class BookshelfListView(LoginRequiredMixin, generic.ListView):
    model = Bookshelf
    template_name = 'book_list.html'
    paginate_by = 3

    # def get_queryset(self):
    #     books = Bookshelf.objects.filter(user=self.request.user).order_by('-updated_at')
    #     return books

    def get_queryset(self):
        q_word = self.request.GET.get('query')

        if q_word:
            books = Bookshelf.objects.filter(
                Q(title__icontains=q_word) | 
                Q(auther__icontains=q_word)|
                Q(group__icontains=q_word),user=self.request.user).order_by('-updated_at')
            return books
        else:
            books = Bookshelf.objects.filter(user=self.request.user).order_by('-updated_at')
            return books


class BookshelfDetailView(LoginRequiredMixin, generic.DetailView):
    model = Bookshelf
    template_name = 'book_detail.html'

class BookshelfCreateView(LoginRequiredMixin, generic.CreateView):
    model = Bookshelf
    template_name = 'book_create.html'
    form_class = BookshelfCreateForm
    success_url = reverse_lazy('bookshelf:book_list')

    def form_valid(self, form):
        bookshelf = form.save(commit=False)
        bookshelf.user = self.request.user
        bookshelf.save()
        messages.success(self.request, '本を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "本の作成に失敗しました。")
        return super().form_invalid(form)

class BookshelfUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Bookshelf
    template_name = 'book_update.html'
    form_class = BookshelfCreateForm
    
    def get_success_url(self):
        return reverse_lazy('bookshelf:book_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, '本の情報を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "本の情報更新に失敗しました。")
        return super().form_invalid(form)

class BookshelfDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Bookshelf
    template_name = 'book_delete.html'
    success_url = reverse_lazy('bookshelf:book_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "本を削除しました。")
        return super().delete(request, *args, **kwargs)

private_bookshelf/bookshelf/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>{% block title %}{% endblock %}</title>
        
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- My styles Bootstrap - Grayscale v6.0.3 -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyles.css' %}" />
        <!-- My style created me -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}" />

        {% block head %}{% endblock %}

    </head>

    <body id="page-top">
        <div id="wrapper">
<!-- Navigation section start-->
            <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
                <div class="container">
                    <a class="navbar-brand js-scroll-trigger" href="{% url 'bookshelf:index' %}">MY BOOK SHELF</a>
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item {% block active_inquiry %}{% endblock %}">
                                <a class="nav-link" href=" {% url 'bookshelf:inquiry' %} ">Inquiry</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item {% block active_bookshelf_list %}{% endblock %}">
                                <a class="nav-link" href="{% url 'bookshelf:book_list' %}">Book List</a>
                            </li>
                            {% endif %}
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" href="{% url 'account_logout' %}">Log Out</a>
                            </li>
                            <li class="nav-item {% block active_user %}{% endblock %}">
                                <a class="nav-link" href="#">{{ user.get_username }}　さん　ようこそ</a>
                            </li>
                            {% else %}
                            <li class="nav-item {% block active_about %}{% endblock %}">
                                <a class="nav-link" href="{% url 'bookshelf:index' %}#projects">About</a>
                            </li>
                            <li class="nav-item {% block active_signup %}{% endblock %}">
                                <a class="nav-link js-scroll-trigger" href="{% url 'account_signup' %}">Sign Up</a>
                            </li>
                            <li class="nav-item {% block active_login %}{% endblock %}">
                                <a class="nav-link js-scroll-trigger" href="{% url 'account_login' %}">Log In</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
<!-- Navigation section end -->
{% block header %}{% endblock %}
<!-- message section start -->
{% if messages %}
            <div class = "container">
                <div class = "row">
                    <div class = "my-div-style w-100">
                        <ul class = "messages" style = "list-style: none;">
                            {% for message in messages %}
                            <li {% if message.tags %}class = "{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
{% endif %}
<!-- message section end -->
{% block contents %}{% endblock %}
<!-- Footer section start -->
            <footer class="footer bg-black small text-center text-white-50">
                <div class="container">Copyright © My Book Shelf 2021</div>
            </footer>
<!-- Footer section end -->
            <!-- Bootstrap core JS-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Third party plugin JS-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
            <!-- Core theme JS-->
            <script src="{% static 'js/scripts.js' %}"></script>
        </div>
    </body>
</html>

private_bookshelf/bookshelf/templates/book_create.html
{% extends "base.html" %}
{% load static %}

{% block title %} 新規作成｜MY BOOK SHELF {% endblock %}

{% block active_bookshelf_list %} active {% endblock %}

{% block contents %}
<div class = "container">
    <div class = "row">
        <div class = "my-div-style w-100">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

private_bookshelf/bookshelf/templates/book_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 本の削除｜MY BOOK SHELF {% endblock %}

{% block active_bookshelf_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-outline-success mt-5" type="submit">削除</button>
                <a class="btn btn-outline-danger mt-5 ml-2" href="{% url 'bookshelf:book_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

private_bookshelf/bookshelf/templates/book_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} 本詳細｜MY BOOK SHELF {% endblock %}

{% block active_bookshelf_list %} active {% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-3">
                <strong>タイトル</strong>
            </div>
            <div class="col-9">
                {{ object.title }}
            </div>
        </div>
        <hr>
        <div class="flexlistd">
            <div class="rowdetail">
                <div class="col-12">
                    <strong>写真</strong>
                </div>
                <div class="col-8">
                    {% if object.photo %}
                        <img src="{{ object.photo.url }}" width="180" height="200">
                    {% else %}
                        <img src="{% static '/assets/img/noImage.jpg' %}" width="180" height="200">
                    {% endif %}
                </div>
            </div>
            <hr>
            <div class="flexlistdd">
                <div class="rowr">
                    <div class="col-12">
                        <strong>著作者</strong>
                    </div>
                    <div class="col-12">
                        {{ object.auther }}
                    </div>
                </div>

                <hr>

                <div class="rowr">
                    <div class="col-12">
                        <strong>出版社</strong>
                    </div>
                    <div class="col-12">
                        {{ object.publisher }}
                    </div>
                </div>

                <hr>

                <div class="rowr">
                    <div class="col-12">
                        <strong>ISBN</strong>
                    </div>
                    <div class="col-12">
                        {{ object.isbnum }}
                    </div>
                </div>
            </div>
        </div>
            <hr>
            <div class="rowcom">
                <div class="col-3">
                    <strong>コメント</strong>
                </div>
                <div class="col-9">
                    {{ object.comment|linebreaksbr }}
                </div>
            </div>
            <hr>


            <div class="row">
                <div class="col-3">
                    <strong>しおり</strong>
                </div>
                <div class="col-9">
                    {{ object.readpage }}
                </div>
            </div>

            <hr>

            <div class="row">
                <div class="col-3">
                    <strong>グループ</strong>
                </div>
                <div class="col-9">
                    {{ object.group }}
                </div>
            </div>

            <hr>
            <div class="row">
                <div class="col-3">
                    <strong>評価</strong>
                </div>
                <div class="col-9">
                    {{ object.evaluation }}
                </div>
            </div>

            <hr>

            <div class="row">
                <div class="col-3">
                    <strong>作成日時</strong>
                </div>
                <div class="col-9">
                    {{ object.created_at }}
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <strong>更新日時</strong>
                </div>
                <div class="col-9">
                    {{ object.updated_at }}
                </div>
            </div>

        <a class="btn btn-outline-success mt-5 mb-3" href="{% url 'bookshelf:book_update' object.pk %}">編集</a>
        <a class="btn btn-outline-danger mt-5 ml-2 mb-3" href="{% url 'bookshelf:book_delete' object.pk %}">削除</a>
    </div>
</div>
{% endblock %}

private_bookshelf/bookshelf/templates/book_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} 本一覧｜MY BOOK SHELF {% endblock %}

{% block active_bookshelf_list %} active {% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class = contorigin>
                    <div class="form-inline my-2">
                        <a class="btn btn-outline-primary float-right" href="{% url 'bookshelf:book_create' %}">新規作成</a>
                    </div>
<!-- 検索フォーム start -->
                    <div class="clearfix">
                        <form class="form-inline my-2" method="GET" action="">
                            <input type="text" class="form-control" input name="query" value="{{request.GET.query}}">
                            <button type="submit" value="search" class="btn btn-outline-primary">検索</button>
                        </form>
                    </div>
<!-- 検索フォーム end -->
                </div>

                <hr>

            </div>
<!-- リスト表示 start -->
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for bookshelf in bookshelf_list %}
                    <div class="post-preview">
                        <a href="{% url 'bookshelf:book_detail' bookshelf.pk %}">
                            <div class="flext">
                                <h3 class="post-title">
                                    {{ bookshelf.title }}
                                </h3>
                            </div>
                            <div class="flexlistl">
                                <div>
                                    <div>
                                        <h5 class="post-meta">
                                            {{ bookshelf.auther }}
                                        </h5>
                                        {% if bookshelf.photo %}
                                            <img src="{{ bookshelf.photo.url }}" class="bookimg" height="100" width="80">
                                        {% else %}
                                            <img src="{% static '/assets/img/noImage.jpg' %}" height="100" width="80">
                                        {% endif %}
                                            <h5 class="post-meta">{{ bookshelf.group }}</h5>
                                    </div>
                                </div>
                                <div class="flexlistr">
                                    <div>
                                        <p class="post-meta">{{ bookshelf.comment|truncatechars:10 }}</p>
                                        <p class="post-meta">{{ bookshelf.readpage }}</p>
                                        <p class="post-meta">{{ bookshelf.updated_at }}</p>
                                    </div>

                                </div>
                            </div>
                        </a>
                    </div>
                    <hr>
                {% empty %}
                    <p>本の登録がありません</p>
                {% endfor %}
            </div>
<!-- リスト表示 end -->
<!-- ページネーション処理 start -->
                {% if is_paginated %}
                    <ul class = "pagination">
                        <!--前ページへのリンク-->
                        {% if page_obj.has_previous %}
                            <li class = "page-item">
                                <a class = "page-link" href = "?page = {{ page_obj.previous_page_number }}">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        <!--ページ数表示-->
                        {% for page_num in page_obj.paginator.page_range %}
                            {% if page_obj.number == page_num %}
                                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!--次ページへのリンク-->
                        {% if page_obj.has_next %}
                            <li class = "page-item">
                                <a class = "page-link" href = "?page = {{ page_obj.next_page_number }}">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!-- ページネーション処理 end -->
{% endblock %}

private_bookshelf/bookshelf/templates/book_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 本の更新｜MY BOOK SHELF {% endblock %}

{% block active_bookshelf_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-outline-success" type="submit">更新</button>
                <a class="btn btn-outline-danger ml-2" href="{% url 'bookshelf:book_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

private_bookshelf/bookshelf/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Web上にあなた専用の本棚を保存できるサービス | MY BOOK SHELF{% endblock %}

{% block header %}

<!-- Masthead-->
<header class="masthead">
    <div class="container d-flex h-100 align-items-center">
        <div class="mx-auto text-center">
            <h1 class="mx-auto my-0 text-uppercase">MY BOOK SHELF</h1>
            <h2 class="text-white-50 mx-auto mt-2 mb-5">Let's make your own bookshelf on the WEB!</h2>
            {% if user.is_authenticated %}
            <a class="btn btn-outline-primary js-scroll-trigger" href="{% url 'account_login' %}" >Book list</a>
            {% else %}
            <a class="btn btn-outline-primary js-scroll-trigger" href="{% url 'account_login' %}" >LOG IN</a>
            {% endif %}
        </div>
    </div>
</header>
{% endblock %}

{% block contents %}

<!-- Projects-->
<section class="projects-section bg-light" id="projects">
    <div class="container">
        <!-- Featured Project Row-->
        <div class="row align-items-center no-gutters mb-4 mb-lg-5">
            <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="{% static 'assets/img/bs-top-image.jpg' %}" alt="" /></div>
            <div class="col-xl-4 col-lg-5">
                <div class="featured-text text-center text-lg-left">
                    <h4>本棚を持ち運ぼう！</h4>
                    <p class="text-black-50 mb-0">MY BOOK SHELFはWeb上にあなた専用の本棚を保存できるサービスです。</p>
                </div>
            </div>
        </div>
        <!-- Project One Row-->
        <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
            <div class="col-lg-6"><img class="img-fluid" src="{% static 'assets/img/books-index_image02.jpg' %}" alt="" /></div>
            <div class="col-lg-6">
                <div class="bg-black text-center h-100 project">
                    <div class="d-flex h-100">
                        <div class="project-text w-100 my-auto text-center text-lg-left">
                            <h4 class="text-white">この本持っていたかな？</h4>
                            <p class="mb-0 text-white-50">外出先で困ったことはありませんか？<br>本を登録しておけば、いつでもMY BOOK SHELF で確認することができます。</p>
                            <hr class="d-none d-lg-block mb-0 ml-0" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Project Two Row-->
        <div class="row justify-content-center no-gutters">
            <div class="col-lg-6"><img class="img-fluid" src="{% static 'assets/img/books-index_image01.jpg' %}" alt="" /></div>
            <div class="col-lg-6 order-lg-first">
                <div class="bg-black text-center h-100 project">
                    <div class="d-flex h-100">
                        <div class="project-text w-100 my-auto text-center text-lg-right">
                            <h4 class="text-white">あの本どこに置いたかな？</h4>
                            <p class="mb-0 text-white-50">好きな言葉で検索することができます。本棚の場所を書いておくこともできますし、本棚の場所が必要なければジャンルで分けることもできます。</p>
                            <hr class="d-none d-lg-block mb-0 mr-0" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

private_bookshelf/bookshelf/templates/inquiry.html
{% extends "base.html" %}

{% block title %} お問い合わせ | My Book Shelf {% endblock %}

{% block active_inquiry %} active {% endblock %}

{% block contents %}
<div class = "container">
    <div class = "rowiqry">
        <div class = "offset-sm-1 my-div-style">
            <form method = "post">
                {% csrf_token %}

                {{form.non_field_errors}}

                {% for field in form %}
                    <div class = "form-group row">
                        <label for = "{{ field.id_for_label }}"class="col-sm-3 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class = "col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class = "offset-sm-1 col-sm-8">
                    <button class = "btn btn-primary" type = "submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}